### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [dubzzz/gnu-linux-tips#2]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by dubzzz** [comment]
Hi,
The project is mostly made from a set of notes I took when I setup one of my server. Not sure it can be said 'active'.

**Comment by ghost** [comment]
Hi dubzzz.

> Hi,
> The project is mostly made from a set of notes I took when I setup one of my server. Not sure it can be said 'active'.

thank you for feedback. I will close this issue, you clarified my doubt.

*Have a great day, and thank you for your patience in answering my question.*
